### ISSUE TITLE
OSX compilation error

### ISSUE THREAD

**Issue by vit1251** [narfit66/ncursesw-rs#5]
```
  thread 'main' panicked at 'Unable to find 'panelw' library!!!', /Users/vit1251/.cargo/git/checkouts/ncursesw-rs-b15859baf9b5f199/734fef6/build.rs:48:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by narfit66** [comment]
Hi there @vit1251, how was ncurses installed on your machine and are you sure your installation has the panelw library installed (this is part of the ncurses package)

**Comment by vit1251** [comment]
@narfit66 I use usual macOS installation 11.5.2 with built-in ncurses described at https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man3/ncurses.3x.html

I does not do additional installation and upgrade ncurses package. Does not know about panelw but pkg-config provide 

```
% pkg-config --modversion ncursesw
5.7.20081102
```

**Comment by narfit66** [comment]
@vit1251 The first problem is that this crate only support ncurses ABI 6.1 and above (please see the read me file) and pkg-config is saying you have 5.7 installed.
The second issue is I don't have access to an OSX platform and so i don't know if the building and installation of ncurses that comes with this crate will work for you. The reason this crate comes with a installation and compile option for ncurses is that it uses wide character and extended colour support (it also provided the base ABI supported by this crate) and these are not always complied in on standard installations of ncurses, also as explained in the read me this has only been tested on 64-bit Linux as this is the only development platform i have access to.

**Comment by vit1251** [comment]
@narfit66 I can test on OSX and make port `addwstr` to ncurses-rs (at https://github.com/vit1251/ncurses-rs) and it working but ncurses module does not provide wide chars support.

I don't know if you want to support OSX either, but I also wrote to Apple asking to update ncurses library in their OSX latest distribution or provide a mechanism for updating (i.e. with using package manager or similar solution). I suspect that my request will be ignored, so I hope for you pay attention to a welcome my request.

**Comment by narfit66** [comment]
@vit1251 Hi, first off sorry for the delay in getting back to you on this. I believe that this problem should now be fixed as of the latest git changes (or if using crates.io v0.6.1 of this crate) as NCurses is now being compiled and linked to statically and not using any shared libraries already on the system. This has only been tested against Debian builds but in theory should work on OSX as well.
